### PR TITLE
Implement test to check ListManager configuration is disabled on CD

### PR DESCRIPTION
**Pull request by ArtemNizelnyk**
The test idea comes from the original DiagToolset Tests spreadsheet. I believe those tests don't require approval.
[Copy of ECM DiagToolset Tests.xlsx](https://github.com/Sitecore/Sitecore-Diagnostics-Tool/files/1638998/Copy.of.ECM.DiagToolset.Tests.xlsx)

### CODE REVIEW

**Comment by AlenPelin** [comment]
This is not actual in Sitecore 9 since all configuration changes are done with a web.config switch.

**Comment by ArtemNizelnyk** [comment]
I can limit the test to 8.x versions. Does it have a sense? Otherwise just close the PR.

**Comment by AlenPelin** [comment]
Limiting to 8.x sounds great, please go ahead.

**Comment by ArtemNizelnyk** [comment]
Done.

**Pull request merged**
